#include <stdio.h>
#include <stdlib.h>
#include "../main.h"


int write2xyz(struct Atoms atoms[], char filename[], int NMAX){
  FILE *fptr = fopen(filename, "a");
  if (!fptr){
    perror("write2xyz: fopen");
    return EXIT_FAILURE;
  }
  fprintf(fptr, "%d\n", NMAX);
  fprintf(fptr, "generated by write2xyz\n");
  for (int idx=0, i = 0; i < NMAX; i++){
      fprintf(fptr, "%s %10.7f %10.7f %10.7f\n",
          atoms[idx].symbol,atoms[idx].x, atoms[idx].y, atoms[idx].z);
      idx++;
    }
  fclose(fptr);
  return EXIT_SUCCESS;
}
